### PR TITLE
[FXML-4376] Add missing Libm member Math operations to MathToLibm

### PR DESCRIPTION
**Pull request by cferry-AMD**
Operation | In MathToLibm | Libm member
-- | -- | --
math.absf   (math::AbsFOp) | This PR | X
math.absi   (math::AbsIOp) |   |  
math.acos   (math::AcosOp) | X | X
math.acosh   (math::AcoshOp) | Upstream | X
math.asin   (math::AsinOp) | Upstream | X
math.asinh   (math::AsinhOp) | Upstream | X
math.atan   (math::AtanOp) | X | X
math.atan2   (math::Atan2Op) | X | X
math.atanh   (math::AtanhOp) | Upstream | X
math.cbrt   (math::CbrtOp) | X | X
math.ceil   (math::CeilOp) | X | X
math.copysign   (math::CopySignOp) |   |  
math.cos   (math::CosOp) | X | X
math.cosh   (math::CoshOp) | X | X
math.ctlz   (math::CountLeadingZerosOp) |   |  
math.ctpop   (math::CtPopOp) |   |  
math.cttz   (math::CountTrailingZerosOp) |   |  
math.erf   (math::ErfOp) | X | X
math.exp   (math::ExpOp) | This PR | X
math.exp2   (math::Exp2Op) | This PR | X
math.expm1   (math::ExpM1Op) | X | X
math.floor   (math::FloorOp) | X | X
math.fma   (math::FmaOp) | This PR | X
math.fpowi   (math::FPowIOp) |   | X
math.ipowi   (math::IPowIOp) |   |  
math.log   (math::LogOp) | This PR | X
math.log10   (math::Log10Op) | This PR | X
math.log1p   (math::Log1pOp) | X | X
math.log2   (math::Log2Op) | This PR | X
math.powf   (math::PowFOp) | This PR | X
math.round   (math::RoundOp) | X | X
math.roundeven   (math::RoundEvenOp) | X | X
math.rsqrt   (math::RsqrtOp) |   |  
math.sin   (math::SinOp) | X | X
math.sinh   (math::SinhOp) | Upstream | X
math.sqrt   (math::SqrtOp) | This PR | X
math.tan   (math::TanOp) | X | X
math.tanh   (math::TanhOp) | Upstream | X
math.trunc   (math::TruncOp) | X | X

Legend:
* X = already supported,
* Upstream = part of [upstream changes](https://github.com/llvm/llvm-project/commits/main/mlir/lib/Conversion/MathToLibm/MathToLibm.cpp), absent of `feature/fused-ops`,
* This PR = introduced here.

### CODE REVIEW

**Review by mgehre-amd — APPROVED** [review]

**Comment by cferry-AMD** [comment]
The ops in this PR are the only ones we can do using straightforward calls to `libm` functions.

One exception that is a member of `libm` is `fpowi`. The function for this op is an overload of `pow`, the same as for the `powf` op. 
Due to how IR is emitted by 
However, it is not possible to have overloads in MLIR: using both `powf` and `fpowi` operations would cause invalid IR to be emitted.

**Comment by mgehre-amd** [comment]
I don't quite understand your comment about `math.fpowi`. To which function in `math.h` does it correspond?

**Comment by cferry-AMD** [comment]
> I don't quite understand your comment about `math.fpowi`. To which function in `math.h` does it correspond?

It corresponds to `pow(float, int)` from `<cmath>` which is an overload of `pow(double, double)`. `math.h` (the C standard library header) has the latter only.

I don't see a straightforward way to support overloads in EmitC, because the symbol name uniqueness (per symbol table) comes from MLIR, not from EmitC itself.

**Comment by mgehre-amd** [comment]
> It corresponds to `pow(float, int)` from `<cmath>` which is an overload of `pow(double, double)`. `math.h` (the C standard library header) has the latter only.
> 
> I don't see a straightforward way to support overloads in EmitC, because the symbol name uniqueness (per symbol table) comes from MLIR, not from EmitC itself.

I see. Then we could look into `populateMathAlgebraicSimplificationPatterns`, which can turn `powi` into multiplications for small constant exponents, and if that fails, cast the second operand to float/double?

**Review by mgehre-amd — APPROVED** [review]

**Comment by cferry-AMD** [comment]
That's one way similar to IPowI actually. Let's do this in a separate PR.

**Pull request merged**
